version: '3.8'

services:
  mssql-protheus:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-protheus
    environment:
      SA_PASSWORD: "Totvs@12"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_COLLATION: "Latin1_General_CI_AS"
    ports:
      - "1433:1433"
    volumes: 
      - D:\docker\mssql-protheus:/var/opt/mssql/data #aqui vc deve colocar o caminho do diretório da sua maquina fisica C:\exemplo:/var/opt/mssql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh"]